### ISSUE TITLE
glsl-shaders vs glsl-shader

### ISSUE THREAD

**Issue by johnlee1st** [classicjazz/mpv-config#10]
1. I checked the [mpv documentation](https://mpv.io/manual/stable/#gpu-renderer-options) over and over and kept wondering:
Shouldn't
```
glsl-shaders="~/.config/mpv/shaders/FSRCNNX_x2_8-0-4-1.glsl"
```
be
```
glsl-shader="~/.config/mpv/shaders/FSRCNNX_x2_8-0-4-1.glsl"
```
instead?
I mean, `--glsl-shaders=` is used to load a _list_ of files, while `--glsl-shader=` a file, heh?

2.  This one is a minor typo.
```
# fbo-format is not not supported in gpu-next profile
```
`not not`

**Comment by classicjazz** [comment]
I just pushed a release with updates

Thank you
