### ISSUE TITLE
gpu-next and moltenvk

### ISSUE THREAD

**Issue by salvo-github** [classicjazz/mpv-config#11]
Hey, let me start with saying that i appreciate your effort to create this repo for the mpv configuration on macos. 

I've tried your last version (gpu-next and vulkan) but i can't make it work.

Do you have any advise on how to have it working? 

i'm using moltenvk installed through brew

**Comment by EndlessEden** [comment]
just poking this to suggest you try rebuilding mpv with a more recent build. moltenvk compatibility has been a constant WIP, alongside vulkan support as a whole.
