### ISSUE TITLE
Issue: bwdif is not compatible with vulkan

### ISSUE THREAD

**Issue by EndlessEden** [classicjazz/mpv-config#13]
When vulkan is used, bwdif filter cannot be loaded. bwdif_vulkan must be used instead.

**Comment by classicjazz** [comment]
I changed the parameter in release v.22 to 

deinterlace=yes

Since MPV now uses BWDIF by default, I believe that this will use the correct deinterlacer regardless of platform.

See https://github.com/mpv-player/mpv/pull/13331
