### ISSUE TITLE
shader order

### ISSUE THREAD

**Issue by HedioKojima** [classicjazz/mpv-config#15]
I found that the statement mentioned here before about which comes first, the luma shader or the chroma shader, seems different from that in your configuration file. I'm confused again and hope you can provide an explanation.Thanks

https://github.com/mpv-player/mpv/issues/12483

**Comment by HedioKojima** [comment]
> I found that the statement mentioned here before about which comes first, the luma shader or the chroma shader, seems different from that in your configuration file. I'm confused again and hope you can provide an explanation.thanks
> 
> [mpv-player/mpv#12483](https://github.com/mpv-player/mpv/issues/12483)

**Comment by classicjazz** [comment]
Thanks. I just made some changes to the mpv.conf based on this thread. I also updated the shaders to the latest source files. Please take a look and let me know if there are any issues.

**Comment by HedioKojima** [comment]
Thank you for your work. The configuration file used is very good.
