### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by unculcated** [classicjazz/mpv-config#2]
I used your mpv zip
iMac (Retina 4K, 21.5-inch, 2017)
I didn't change anything
here is the error:

https://pastebin.com/tRtEJupA

**Comment by classicjazz** [comment]
Are you using mpv from github master (the last brew release was over a year ago)? I see a lot of unsupported options.

Also note that it says your hardware may be too slow for the content that you are trying to play.

**Comment by unculcated** [comment]
ok, I just installed the GitHub master, I was using home-brew. I think you might be right.  I think my imac can't handle 60fps too well. 
I loaded a smaller sized film and this is the terminal read out. Is there a way to have the benefits of this config on my current computer? Maybe disabling 60 fps?

mpv /Volumes/storage/Wild\ Strawberries\ 1957\ Criterion\ \(1080p\ Bluray\ x265\ HEVC\ 10bit\ AAC\ 1.0\ Swedish\ Tigole\)/Wild\ Strawberries\ 1957\ Criterion\ \(1080p\ x265\ 10bit\ Tigole\).mkv 
[auto_profiles] Error evaluating: [string "profile 4k30 condition"]:1: attempt to compare number with nil 
[auto_profiles] Error evaluating: [string "profile 4k60 condition"]:1: attempt to compare number with nil 
 (+) Video --vid=1 (*) (hevc 1420x1080 23.976fps)
 (+) Audio --aid=1 --alang=swe (*) (aac 1ch 48000Hz)
     Audio --aid=2 --alang=eng 'Commentary' (aac 1ch 48000Hz)
 (+) Subs  --sid=1 --slang=eng (*) (dvd_subtitle)
Using hardware decoding (videotoolbox).
AO: [coreaudio] 48000Hz mono 1ch floatp
VO: [libmpv] 1420x1080 videotoolbox[p010]
AV: 00:00:02 / 01:32:32 (0%) A-V:  0.004 DS: 0.837/4 Dropped: 37
[+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

**Comment by unculcated** [comment]
Im curious, What system do You have that can run this configuration? I have a pretty nice iMac

**Comment by classicjazz** [comment]
I have a 2017 27in iMac with Radeon Pro 575 4 GB discrete graphics. For my Mac, I need to disable (comment out) glsl-shaders-append="~/.config/mpv/shaders/KrigBilateral.glsl" 

The profiles are written such that different shaders, interpolation, and deinterlacing are enabled depending on a video asset's resolution and interlacing. For example, upscaling of OTA television video works reasonably well (but not perfectly) for me. For traditional video resolutions, MPV may still throw errors particularly regarding video interlacing. 

The Strawberries video aspect ratio is nonstandard (1420x1080). So, it _should_ be using the default profile. 

The biggest issue with using MacOS is that it is limited to an obsolete OpenGL backend. To get better performance, a Metal 2 backend needs to be created for MPV / libplacebo.

**Comment by unculcated** [comment]
So, If I wanted to hook up something to a 4k television. Is there something out there ,a stand alone box perhaps,  that can play mpv and more importantly mkv at 4k?

**Comment by unculcated** [comment]
Maybe raspberry pi and linux setup?

**Comment by classicjazz** [comment]
Plex on an Apple TV 4K can play 4K HDR if you enable the experimental player (MPV).

**Comment by unculcated** [comment]
oh, I guess there must be tons of boxes out there. always think it terms of computer, but maybe that's the wrong angle. Thanks for the help
