### ISSUE TITLE
Apple TV vs 2017 iMac

### ISSUE THREAD

**Issue by unculcated** [classicjazz/mpv-config#3]
I had a discussion here with you about the Apple TV box. That tiny box. Why is it better equipped to play 4k than an iMac with a faster cpu? Is the it the gpu power?  Seems like a rip off to computer buyers

**Comment by classicjazz** [comment]
You asked my recommendation for a settop box to play 4K. Given you are already committed to the Apple ecosystem, I recommended the Apple TV 4K. In addition to 4K SDR, it also renders 4K HDR (both DolbyVision and HDR10).

I believe that your iMac would also output 4K HDR to an external monitor, based on its tech specs.

There is an additional software dependency: I believe Plex wrote a Metal "bridge" to properly handle HDR content. I know that HDR works on Apple TV 4K works. I haven't tested connecting an iMac to an external display.

The other advantage of an Apple TV 4K is all the other 4K HDR content sources that you can choose from such as Netflix and Amazon Prime. And Dolby Atmos audio.

**Comment by unculcated** [comment]
thanks
