### ISSUE TITLE
480p/360p files seem to be greeny-blue and are distorted/sized wrong

### ISSUE THREAD

**Issue by radiosilence** [classicjazz/mpv-config#4]
I can't really give an example file due to copyright laws, but when I play certain series rips (old ones), the colour is almost totally gone. This is using auto-profiles script.

Edit: Initially said just AVI, but tried with an x264 MKV file, too and it happens.

For the MKV

With mpv-config:
```
VO: [libmpv] 720x444 => 1023x444 videotoolbox[nv12]
```

Without (stock config)
```
[vo] 720x444 => 1023x444 yuv420p
```

Fixed if I comment out
```
scale=ewa_lanczos
```

**Comment by aaronsewall** [comment]
I found this post with a workaround using scale-radius
https://github.com/mpv-player/mpv/issues/4607#issuecomment-613695758
