### ISSUE TITLE
Not working in gpu-next

### ISSUE THREAD

**Issue by Trinity3e** [classicjazz/mpv-config#8]
Hello, the shader works in vo=gpu as expected, but in vo=gpu-next both it and chroma scaling are operating. It's possible that the final scaling doesn't work and the cscale fills in.

**Comment by classicjazz** [comment]
With the recent updates to mpv v0.37, I updated the config file and shaders and tested them on MacOS 14.1 with libplacebo and MoltenVK. 

Please let me know if you find any issues with v0.2 release of the new config and shaders.

**Comment by Trinity3e** [comment]
Appreciate it, image quality is good, but in mpv i still see an external chroma stage of vert and horiz upscasling.

**Comment by Trinity3e** [comment]
Okay so something is weird with mpv, when i use the prescaler ravu-zoom-ar-r3.hook from your config, i see no external chroma scale stage on neither KrigBilateral nor CfL_Prediction, they work correctly. By the way, which would you recommend in theory?
I think i will use this ravu combo for the low res configs and ditch fsrcnnx, just with nlmeans in front.
