### ISSUE TITLE
GPU usage 

### ISSUE THREAD

**Issue by Jeanlafonaine** [classicjazz/mpv-config#9]
Hello

I'm using your mpv config and shaders before the 0.37 update of MPV. Everything runs smoothly in general but my GPU usage on my macbook pro m2 pro always reaches 90% just for watching a episode of 45 min. 

I was wondering if this GPU usage was normal and if there wasn't any risk in long term use for my macbook battery 

Thanks in advance for your feedback when you can

**Comment by classicjazz** [comment]
On a Apple Silicon-based Mac, I recommend mpv 0.37 and using vo_gpu_next, libplacebo, Vulkan & MoltenVK.

The 0.2 release uses the FSRCNNX_x2_8 and KrigBilateral shaders. Upscaling a 1080p (H264) video on my M1 Mac uses ~45% CPU and 58% GPU. Playback of a 4k (HEVC) video uses 37% of CPU and 24% of GPU (per Activity Monitor).

On the master, I am experimenting with newly updated RAVU and CfL shaders. Upscaling a 1080p video on my M1 Mac uses ~42% CPU and 33% GPU. Playback of a 4k video uses 41% of CPU and 37% of GPU.

To better interpret these percentages, I recommend reading https://eclecticlight.co/2022/08/13/activity-monitor-meanings-and-misleadings/
